name: Build Verus Desktop Win

on:
  push:
    branches: [main, master, release/*]
  pull_request:
    branches: [master]

env:
  DEFAULT_VERUSCOIN_BRANCH: release
  VERUS_VERSION: 1.2.12-2
  VERUSCOIN_VERSION: 1.2.12-2
  KOMODO_VERSION: 0.9.0
  KOMODO_DOWNLOAD_URL: https://github.com/KomodoPlatform/komodo/releases/download
  PIRATE_VERSION: 5.9.0
  PIRATE_DOWNLOAD_URL: https://github.com/PirateNetwork/pirate/releases/download
  BINARY_SOURCE: VerusCoin
  NODE_OPTIONS: --openssl-legacy-provider

jobs:
  build-windows-cross:
    runs-on: ubuntu-latest
    container:
      image: asherd/agama-builder:windows
    env:
      KOMODO_CLI_PACKAGE: komodo-${KOMODO_VERSION}-win.zip
      KOMODO_CLI_SHA256: 0b36821ebccdaf6bc060dc31083e6d8f48f7f8bc35e519b127bf1ccc05cf9890
      PIRATE_CLI_PACKAGE: pirate-cli-windows-v${PIRATE_VERSION}.zip
      PIRATE_CLI_SHA256: deb338bf2bcabfdb32be3c13dfaed78d83749fbae9d3985e47cb001ff058bb3f
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Setup Wine environment
      run: |
        # Настраиваем Wine для работы в CI
        export WINEPREFIX=/tmp/wineprefix
        export WINEARCH=win64
        mkdir -p $WINEPREFIX
        # Инициализируем Wine
        wineboot --init
        # Даем время на инициализацию
        sleep 5
        
    - name: Setup environment
      run: |
        if [ -z "${UPSTREAM_CLI_BRANCH}" ]; then 
          export VERUS_CLI_WINDOWS="${BINARY_SOURCE}/${DEFAULT_VERUSCOIN_BRANCH}/Windows/Verus-CLI-Windows-v${VERUSCOIN_VERSION}.zip"
        else
          export VERUS_CLI_WINDOWS="${UPSTREAM_TRIGGER}/${UPSTREAM_CLI_BRANCH}/Windows/Verus-CLI-Windows-v${VERUSCOIN_VERSION}.zip"
        fi
        
    - name: Build React GUI
      run: |
        cd gui/Verus-Desktop-GUI/react
        yarn install
        yarn run build
        cd ../../..
        
    - name: Setup binaries directory
      run: |
        mkdir -p assets/bin/win64/komodod
        mkdir -p assets/bin/win64/pirated

    - name: Setup API keys
      run: |
        sed -i "s/process.env.INFURA_PROJECT_ID/'${{ secrets.INFURA_PROJECT_ID }}'/g" keys/infura.js
        sed -i "s/process.env.ETHERSCAN_API_KEY/'${{ secrets.ETHERSCAN_KEY }}'/g" keys/etherscan.js
        
    - name: Install main dependencies
      run: yarn install
      
    - name: Build Windows application with proper Wine config
      run: |
        # Настраиваем переменные окружения для Wine
        export WINEPREFIX=/tmp/wineprefix
        export WINEARCH=win64
        export HOME=/tmp
        
        # Инициализируем Wine
        wineboot --init
        sleep 10
        
        # Устанавливаем виртуальный дисплей
        export DISPLAY=:99
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        
        # Собираем Windows версию
        yarn run dist-win
      
    - name: Check built artifacts
      run: |
        echo "=== Windows Build Artifacts ==="
        ls -la dist/
        echo "=== File Details ==="
        file dist/* || true
        echo "=== File Sizes ==="
        du -h dist/*
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: verus-desktop-windows-cross
        path: dist/
        retention-days: 30
